### ISSUE TITLE
Requesting craft from terminal results in game exiting

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [CyclopsMC/IntegratedTerminals#123]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft exits when requesting a craft via terminal

When requesting a craft you get to the  select amount screen, and on hitting next the game exits reporting:

> Connection Lost
> Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:custom_payload`

Setup is: Mekanism personal barrel w/ honey bottles connected to a network via item interface. Other objects on the network are one storage terminal, and a crafter connected to a crafting table. Recipe is 4x honey bottles = 1 honey block. (Intended to recycle bottles in a productive bees farm not that this matters.)

#### Steps to reproduce the problem:

1. Reproduce network described above.
2. Request the craft of a honey block.
3. Hit next.

#### Expected behaviour:

Minecraft not to exit to the title screen and a craft of a honey block to be scheduled.

____

#### Versions:

- This mod: 1.4.13
- Minecraft: 1.21 (All the Mods 10 version 0.17)
- Forge: NeoForge 21.0.114-beta

#### Log file:

https://gist.github.com/WhiteFire-Sondergaard/e4ecfda6777f31d35f741c6a58b708a7

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self:

```
[22Jul2024 12:47:06.450] [Netty Server IO #1/ERROR] [net.minecraft.network.Connection/]: Exception caught in connection
io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:custom_payload'
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:38) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:31) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar%23148!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar%23148!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23148!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar%23150!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar%23150!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23149!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23149!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23149!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar%23154!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23149!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23149!/:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.RuntimeException: Failed decoding custom payload integratedterminals:terminal_storage_ingredient_open_crafting_plan_gui: org.cyclops.cyclopscore.network.PacketHandler$PacketCodecException: An exception occurred during decoding of packet org.cyclops.integratedterminals.network.packet.CancelCraftingJobPacket@5a7a7306
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:55) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	... 28 more
Caused by: org.cyclops.cyclopscore.network.PacketHandler$PacketCodecException: An exception occurred during decoding of packet org.cyclops.integratedterminals.network.packet.CancelCraftingJobPacket@5a7a7306
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketBase.lambda$getCodec$0(PacketBase.java:82) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$2.decode(StreamCodec.java:37) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:53) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	... 28 more
Caused by: net.minecraft.nbt.ReportedNbtException: Loading NBT data
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:198) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.NbtIo.readAnyTag(NbtIo.java:157) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:537) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:526) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:521) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec$12.decode(PacketCodec.java:254) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec.lambda$decode$1(PacketCodec.java:585) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec.loopCodecFields(PacketCodec.java:565) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec.decode(PacketCodec.java:584) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketBase.lambda$getCodec$0(PacketBase.java:80) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$2.decode(StreamCodec.java:37) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:53) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	... 28 more
Caused by: java.io.IOException: Invalid tag id: -1
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.TagType$1.createException(TagType.java:58) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.TagType$1.load(TagType.java:63) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.TagType$1.load(TagType.java:56) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:193) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.nbt.NbtIo.readAnyTag(NbtIo.java:157) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:537) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:526) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:521) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec$12.decode(PacketCodec.java:254) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec.lambda$decode$1(PacketCodec.java:585) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec.loopCodecFields(PacketCodec.java:565) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketCodec.decode(PacketCodec.java:584) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/cyclopscore@1.19.4/org.cyclops.cyclopscore.network.PacketBase.lambda$getCodec$0(PacketBase.java:80) ~[CyclopsCore-1.21-neoforge-1.19.4.jar%23389!/:1.19.4]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$2.decode(StreamCodec.java:37) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:53) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21-20240613.152323-srg.jar%23349!/:?]
	... 28 more
```
