### ISSUE TITLE
Crash when sorting by item count.

### ISSUE THREAD

**Issue by Unbox101** [CyclopsMC/IntegratedTerminals#15]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I boot up my game and enter my world I open up my crafting terminal and click sort by item count and it crashes.

#### Steps to reproduce the problem:

I just open my storage terminal and click the sort by item count button then it freezes for a bit then the game window completely closes.

#### Expected behaviour:

It used to sort by item count just fine? But now it crashes every time without fail.

____

#### Versions:

- This mod: 1.0.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2795

#### Log file:

https://pastebin.com/4u22exB7

**Comment by rubensworks** [comment]
Note to self:

```
java.lang.NullPointerException: Rendering screen
        at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:24)
        at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:74)
        at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:74)
        at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:18)
        at org.cyclops.commoncapabilities.ingredient.IngredientHelpers.compareTags(IngredientHelpers.java:37)
        at org.cyclops.commoncapabilities.ingredient.IngredientMatcherItemStack.compare(IngredientMatcherItemStack.java:122)
        at org.cyclops.commoncapabilities.ingredient.IngredientMatcherItemStack.compare(IngredientMatcherItemStack.java:14)
        at java.util.Comparator.lambda$thenComparing$36697e65$1(Unknown Source)
```

**Comment by rubensworks** [comment]
This was a bug in CommonCapabilities, just pushed a new release for that.
