### ISSUE TITLE
Server crash when autocrafting on portable terminal

### ISSUE THREAD

**Issue by RGFTheCoder** [CyclopsMC/IntegratedTerminals#68]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash when trying to use autocraft on a portable terminal, likely because server tries to call client function. (Happened w/ InventoryPets as well)

#### Steps to reproduce the problem:

1. Set up a basic network with Integrated Tunnels and Integrated Crafting
2. Add an Omnidirectional tunnel
3. Activate Portable Terminal
4. Click on the "craft" icon of some item

#### Expected behaviour:

Server doesn't crash

____

#### Versions:

- This mod: 1.2.1
- Minecraft: 1.16.5
- Forge: 36.1.0

#### Log file:

<details>
<summary>Logs</summary>
<pre>
[22:53:46] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.network.PacketBuffer.func_218666_n()'
        at org.cyclops.integratedterminals.core.terminalstorage.location.TerminalStorageLocationItem.readFromPacketBuffer(TerminalStorageLocationItem.java:114) ~[integratedterminals:1.2.1] {re:classloading}
        at org.cyclops.integratedterminals.core.terminalstorage.location.TerminalStorageLocationItem.readFromPacketBuffer(TerminalStorageLocationItem.java:26) ~[integratedterminals:1.2.1] {re:classloading}
        at org.cyclops.integratedterminals.network.packet.TerminalStorageIngredientCraftingOptionDataPacketAbstract.decode(TerminalStorageIngredientCraftingOptionDataPacketAbstract.java:73) ~[integratedterminals:1.2.1] {re:classloading,pl:runtimedistcleaner:A}
        at org.cyclops.cyclopscore.network.PacketHandler.lambda$register$2(PacketHandler.java:69) ~[cyclopscore:1.11.5] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[forge:?] {re:classloading}
        at java.util.Optional.map(Optional.java:265) ~[?:?] {}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) ~[forge:?] {re:classloading}
        at java.util.Optional.map(Optional.java:265) ~[?:?] {}
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) ~[forge:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
</pre>
</details>

**Comment by rubensworks** [comment]
Thanks for reporting!
